#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("PlusSample.Resource", IsApplication=true)]

namespace PlusSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050009
			public const int common_action_bar_splitter = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int common_signin_btn_dark_text_default = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int common_signin_btn_dark_text_disabled = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_signin_btn_dark_text_focused = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int common_signin_btn_dark_text_pressed = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int common_signin_btn_default_background = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int common_signin_btn_light_text_default = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int common_signin_btn_light_text_disabled = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int common_signin_btn_light_text_focused = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int common_signin_btn_light_text_pressed = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int common_signin_btn_text_dark = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int common_signin_btn_text_light = 2131034123;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_ic_googleplayservices = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_signin_btn_icon_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_signin_btn_icon_disabled_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_signin_btn_icon_disabled_focus_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_signin_btn_icon_disabled_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_signin_btn_icon_focus_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_signin_btn_icon_focus_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_signin_btn_icon_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_signin_btn_icon_normal_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_signin_btn_icon_normal_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_signin_btn_icon_pressed_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_signin_btn_icon_pressed_light = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_signin_btn_text_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_text_disabled_dark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_text_disabled_focus_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_text_disabled_focus_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_text_disabled_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_text_focus_dark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_text_focus_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_text_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_text_normal_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_text_normal_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_signin_btn_text_pressed_dark = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_signin_btn_text_pressed_light = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_launcher = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_plusone_medium_off_client = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_plusone_small_off_client = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_plusone_standard_off_client = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_plusone_tall_off_client = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int Icon = 2130837535;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int adjust_height = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int adjust_width = 2131230721;
			
			// aapt resource value: 0x7f080015
			public const int change_locale = 2131230741;
			
			// aapt resource value: 0x7f080003
			public const int moment_list = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int moment_title = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int moment_type = 2131230724;
			
			// aapt resource value: 0x7f080002
			public const int none = 2131230722;
			
			// aapt resource value: 0x7f080006
			public const int person_list = 2131230726;
			
			// aapt resource value: 0x7f080008
			public const int plus_one_medium_button = 2131230728;
			
			// aapt resource value: 0x7f080007
			public const int plus_one_small_button = 2131230727;
			
			// aapt resource value: 0x7f08000b
			public const int plus_one_standard_ann_button = 2131230731;
			
			// aapt resource value: 0x7f08000a
			public const int plus_one_standard_button = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int plus_one_tall_button = 2131230729;
			
			// aapt resource value: 0x7f080013
			public const int revoke_access_button = 2131230739;
			
			// aapt resource value: 0x7f08000e
			public const int scope_selection_toggle = 2131230734;
			
			// aapt resource value: 0x7f08000d
			public const int send_interactive_button = 2131230733;
			
			// aapt resource value: 0x7f080011
			public const int server_auth_code_disabled = 2131230737;
			
			// aapt resource value: 0x7f080010
			public const int server_auth_code_reset_button = 2131230736;
			
			// aapt resource value: 0x7f08000c
			public const int share_prefill_edit = 2131230732;
			
			// aapt resource value: 0x7f08000f
			public const int sign_in_button = 2131230735;
			
			// aapt resource value: 0x7f080014
			public const int sign_in_status = 2131230740;
			
			// aapt resource value: 0x7f080012
			public const int sign_out_button = 2131230738;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int google_play_services_version = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int list_moments_activity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int main_list_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int moment_row = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int multi_moment_activity = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int person_list_activity = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int plus_one_activity = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int share_activity = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int sign_in_activity = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int main_activity_menu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040022
			public const int app_name = 2130968610;
			
			// aapt resource value: 0x7f040001
			public const int auth_google_play_services_client_facebook_display_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int auth_google_play_services_client_google_display_name = 2130968576;
			
			// aapt resource value: 0x7f040023
			public const int change_locale = 2130968611;
			
			// aapt resource value: 0x7f040004
			public const int common_android_wear_notification_needs_update_text = 2130968580;
			
			// aapt resource value: 0x7f040011
			public const int common_android_wear_update_text = 2130968593;
			
			// aapt resource value: 0x7f04000f
			public const int common_android_wear_update_title = 2130968591;
			
			// aapt resource value: 0x7f04001f
			public const int common_google_play_services_api_unavailable_text = 2130968607;
			
			// aapt resource value: 0x7f04000d
			public const int common_google_play_services_enable_button = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int common_google_play_services_enable_text = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int common_google_play_services_enable_title = 2130968587;
			
			// aapt resource value: 0x7f040006
			public const int common_google_play_services_error_notification_requested_by_msg = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public const int common_google_play_services_install_button = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int common_google_play_services_install_text_phone = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int common_google_play_services_install_text_tablet = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int common_google_play_services_install_title = 2130968583;
			
			// aapt resource value: 0x7f040017
			public const int common_google_play_services_invalid_account_text = 2130968599;
			
			// aapt resource value: 0x7f040016
			public const int common_google_play_services_invalid_account_title = 2130968598;
			
			// aapt resource value: 0x7f040005
			public const int common_google_play_services_needs_enabling_title = 2130968581;
			
			// aapt resource value: 0x7f040015
			public const int common_google_play_services_network_error_text = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int common_google_play_services_network_error_title = 2130968596;
			
			// aapt resource value: 0x7f040003
			public const int common_google_play_services_notification_needs_update_title = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int common_google_play_services_notification_ticker = 2130968578;
			
			// aapt resource value: 0x7f040021
			public const int common_google_play_services_sign_in_failed_text = 2130968609;
			
			// aapt resource value: 0x7f040020
			public const int common_google_play_services_sign_in_failed_title = 2130968608;
			
			// aapt resource value: 0x7f040018
			public const int common_google_play_services_unknown_issue = 2130968600;
			
			// aapt resource value: 0x7f04001a
			public const int common_google_play_services_unsupported_text = 2130968602;
			
			// aapt resource value: 0x7f040019
			public const int common_google_play_services_unsupported_title = 2130968601;
			
			// aapt resource value: 0x7f04001b
			public const int common_google_play_services_update_button = 2130968603;
			
			// aapt resource value: 0x7f040010
			public const int common_google_play_services_update_text = 2130968592;
			
			// aapt resource value: 0x7f04000e
			public const int common_google_play_services_update_title = 2130968590;
			
			// aapt resource value: 0x7f040013
			public const int common_google_play_services_updating_text = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int common_google_play_services_updating_title = 2130968594;
			
			// aapt resource value: 0x7f04001e
			public const int common_open_on_phone = 2130968606;
			
			// aapt resource value: 0x7f04001c
			public const int common_signin_button_text = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int common_signin_button_text_long = 2130968605;
			
			// aapt resource value: 0x7f04002c
			public const int default_status = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public const int greeting_status = 2130968621;
			
			// aapt resource value: 0x7f04002f
			public const int greeting_status_error = 2130968623;
			
			// aapt resource value: 0x7f04002e
			public const int greeting_status_sign_in_required = 2130968622;
			
			// aapt resource value: 0x7f040024
			public const int list_moments_title = 2130968612;
			
			// aapt resource value: 0x7f040030
			public const int loading_status = 2130968624;
			
			// aapt resource value: 0x7f040047
			public const int offline_access_disabled = 2130968647;
			
			// aapt resource value: 0x7f040043
			public const int plus_example_deep_link_id = 2130968643;
			
			// aapt resource value: 0x7f040044
			public const int plus_example_deep_link_url = 2130968644;
			
			// aapt resource value: 0x7f040045
			public const int plus_generic_error = 2130968645;
			
			// aapt resource value: 0x7f04003f
			public const int plus_one_medium_name = 2130968639;
			
			// aapt resource value: 0x7f04003e
			public const int plus_one_small_name = 2130968638;
			
			// aapt resource value: 0x7f040042
			public const int plus_one_standard_ann_name = 2130968642;
			
			// aapt resource value: 0x7f040041
			public const int plus_one_standard_name = 2130968641;
			
			// aapt resource value: 0x7f040040
			public const int plus_one_tall_name = 2130968640;
			
			// aapt resource value: 0x7f04003d
			public const int plus_remove_moment_status = 2130968637;
			
			// aapt resource value: 0x7f040038
			public const int plus_write_moment_status = 2130968632;
			
			// aapt resource value: 0x7f04003b
			public const int plus_write_moment_status_auth_error = 2130968635;
			
			// aapt resource value: 0x7f04003a
			public const int plus_write_moment_status_cached = 2130968634;
			
			// aapt resource value: 0x7f04003c
			public const int plus_write_moment_status_error = 2130968636;
			
			// aapt resource value: 0x7f040039
			public const int plus_write_moment_status_success = 2130968633;
			
			// aapt resource value: 0x7f040046
			public const int progress_message = 2130968646;
			
			// aapt resource value: 0x7f040028
			public const int revoke_access_button_name = 2130968616;
			
			// aapt resource value: 0x7f040037
			public const int revoke_access_error_status = 2130968631;
			
			// aapt resource value: 0x7f040036
			public const int revoke_access_status = 2130968630;
			
			// aapt resource value: 0x7f040025
			public const int send_interactive_button_name = 2130968613;
			
			// aapt resource value: 0x7f040029
			public const int server_auth_code_required_label = 2130968617;
			
			// aapt resource value: 0x7f040048
			public const int server_client_id = 2130968648;
			
			// aapt resource value: 0x7f04002b
			public const int share_prefill_text = 2130968619;
			
			// aapt resource value: 0x7f04002a
			public const int share_title = 2130968618;
			
			// aapt resource value: 0x7f040035
			public const int sign_in_error_status = 2130968629;
			
			// aapt resource value: 0x7f040026
			public const int sign_in_profile_label = 2130968614;
			
			// aapt resource value: 0x7f040027
			public const int sign_out_button_name = 2130968615;
			
			// aapt resource value: 0x7f040032
			public const int signed_in_status = 2130968626;
			
			// aapt resource value: 0x7f040034
			public const int signed_out_status = 2130968628;
			
			// aapt resource value: 0x7f040031
			public const int signing_in_status = 2130968625;
			
			// aapt resource value: 0x7f040033
			public const int unknown_person = 2130968627;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[]
			{
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
