#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("AdMob.Resource", IsApplication=true)]

namespace AdMob
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int adSize = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int adSizes = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int adUnitId = 2130771970;
			
			// aapt resource value: 0x7f010005
			public const int circleCrop = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int imageAspectRatio = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int imageAspectRatioAdjust = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060009
			public const int common_action_bar_splitter = 2131099657;
			
			// aapt resource value: 0x7f060000
			public const int common_signin_btn_dark_text_default = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int common_signin_btn_dark_text_disabled = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_signin_btn_dark_text_focused = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int common_signin_btn_dark_text_pressed = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int common_signin_btn_default_background = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int common_signin_btn_light_text_default = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int common_signin_btn_light_text_disabled = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_signin_btn_light_text_focused = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int common_signin_btn_light_text_pressed = 2131099653;
			
			// aapt resource value: 0x7f06000a
			public const int common_signin_btn_text_dark = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int common_signin_btn_text_light = 2131099659;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080000
			public const int activity_horizontal_margin = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int activity_vertical_margin = 2131230721;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_ic_googleplayservices = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_signin_btn_icon_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_signin_btn_icon_disabled_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_signin_btn_icon_disabled_focus_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_signin_btn_icon_disabled_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_signin_btn_icon_focus_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_signin_btn_icon_focus_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_signin_btn_icon_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_signin_btn_icon_normal_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_signin_btn_icon_normal_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_signin_btn_icon_pressed_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_signin_btn_icon_pressed_light = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_signin_btn_text_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_text_disabled_dark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_text_disabled_focus_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_text_disabled_focus_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_text_disabled_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_text_focus_dark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_text_focus_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_text_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_text_normal_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_text_normal_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_signin_btn_text_pressed_dark = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_signin_btn_text_pressed_light = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_plusone_medium_off_client = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_plusone_small_off_client = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_plusone_standard_off_client = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_plusone_tall_off_client = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int Icon = 2130837534;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090004
			public const int adView = 2131296260;
			
			// aapt resource value: 0x7f090000
			public const int adjust_height = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int adjust_width = 2131296257;
			
			// aapt resource value: 0x7f090005
			public const int linearLayout = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int loadButton = 2131296262;
			
			// aapt resource value: 0x7f090003
			public const int mainLayout = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int none = 2131296258;
			
			// aapt resource value: 0x7f090007
			public const int showButton = 2131296263;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int google_play_services_version = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_banner_code_ad_listener = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_banner_xml = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_interstitial = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int accept = 2131034114;
			
			// aapt resource value: 0x7f050029
			public const int ad_unit_id = 2131034153;
			
			// aapt resource value: 0x7f050028
			public const int app_name = 2131034152;
			
			// aapt resource value: 0x7f050007
			public const int auth_google_play_services_client_facebook_display_name = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int auth_google_play_services_client_google_display_name = 2131034118;
			
			// aapt resource value: 0x7f05002d
			public const int banner_in_code = 2131034157;
			
			// aapt resource value: 0x7f05002c
			public const int banner_in_xml = 2131034156;
			
			// aapt resource value: 0x7f05000a
			public const int common_android_wear_notification_needs_update_text = 2131034122;
			
			// aapt resource value: 0x7f050017
			public const int common_android_wear_update_text = 2131034135;
			
			// aapt resource value: 0x7f050015
			public const int common_android_wear_update_title = 2131034133;
			
			// aapt resource value: 0x7f050025
			public const int common_google_play_services_api_unavailable_text = 2131034149;
			
			// aapt resource value: 0x7f050013
			public const int common_google_play_services_enable_button = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int common_google_play_services_enable_text = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int common_google_play_services_enable_title = 2131034129;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_play_services_error_notification_requested_by_msg = 2131034124;
			
			// aapt resource value: 0x7f050010
			public const int common_google_play_services_install_button = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int common_google_play_services_install_text_phone = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int common_google_play_services_install_text_tablet = 2131034127;
			
			// aapt resource value: 0x7f05000d
			public const int common_google_play_services_install_title = 2131034125;
			
			// aapt resource value: 0x7f05001d
			public const int common_google_play_services_invalid_account_text = 2131034141;
			
			// aapt resource value: 0x7f05001c
			public const int common_google_play_services_invalid_account_title = 2131034140;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_play_services_needs_enabling_title = 2131034123;
			
			// aapt resource value: 0x7f05001b
			public const int common_google_play_services_network_error_text = 2131034139;
			
			// aapt resource value: 0x7f05001a
			public const int common_google_play_services_network_error_title = 2131034138;
			
			// aapt resource value: 0x7f050009
			public const int common_google_play_services_notification_needs_update_title = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int common_google_play_services_notification_ticker = 2131034120;
			
			// aapt resource value: 0x7f050027
			public const int common_google_play_services_sign_in_failed_text = 2131034151;
			
			// aapt resource value: 0x7f050026
			public const int common_google_play_services_sign_in_failed_title = 2131034150;
			
			// aapt resource value: 0x7f05001e
			public const int common_google_play_services_unknown_issue = 2131034142;
			
			// aapt resource value: 0x7f050020
			public const int common_google_play_services_unsupported_text = 2131034144;
			
			// aapt resource value: 0x7f05001f
			public const int common_google_play_services_unsupported_title = 2131034143;
			
			// aapt resource value: 0x7f050021
			public const int common_google_play_services_update_button = 2131034145;
			
			// aapt resource value: 0x7f050016
			public const int common_google_play_services_update_text = 2131034134;
			
			// aapt resource value: 0x7f050014
			public const int common_google_play_services_update_title = 2131034132;
			
			// aapt resource value: 0x7f050019
			public const int common_google_play_services_updating_text = 2131034137;
			
			// aapt resource value: 0x7f050018
			public const int common_google_play_services_updating_title = 2131034136;
			
			// aapt resource value: 0x7f050024
			public const int common_open_on_phone = 2131034148;
			
			// aapt resource value: 0x7f050022
			public const int common_signin_button_text = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int common_signin_button_text_long = 2131034147;
			
			// aapt resource value: 0x7f050005
			public const int create_calendar_message = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int create_calendar_title = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int decline = 2131034115;
			
			// aapt resource value: 0x7f05002e
			public const int interstitial = 2131034158;
			
			// aapt resource value: 0x7f05002b
			public const int interstitial_not_ready = 2131034155;
			
			// aapt resource value: 0x7f05002a
			public const int load_interstitial = 2131034154;
			
			// aapt resource value: 0x7f050001
			public const int store_picture_message = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int store_picture_title = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040001
			public const int AppBaseTheme = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int AppTheme = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int Theme_IAPTheme = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[]
			{
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adSizes = 1;
			
			// aapt resource value: 2
			public const int AdsAttrs_adUnitId = 2;
			
			public static int[] LoadingImageView = new int[]
			{
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
